# Generated by Django 5.0.4 on 2024-05-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splidapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admin_id',
        ),
        migrations.AddField(
            model_name='group',
            name='admin_id',
            field=models.ManyToManyField(related_name='admin_of_groups', to='splidapp.user'),
        ),
    ]
