# Generated by Django 5.0.4 on 2024-05-12 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splidapp', '0003_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admin_id',
        ),
        migrations.AddField(
            model_name='group',
            name='admin_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='splidapp.user'),
            preserve_default=False,
        ),
    ]
