# Generated by Django 5.0.4 on 2024-05-12 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splidapp', '0005_alter_groupmembers_user_id_alter_expense_user_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user_id',
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_for',
            field=models.ManyToManyField(related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
